### ISSUE TITLE
Crit damage% modifier bugged? (applying too much bonus)

### ISSUE THREAD

**Issue by Bladewhisker** [Jofairden/EvenMoreModifiers#10]
For some reason when i have any instance of crit damage increase modifier, it increases crit damage by a LOT (the damage in the picture should be around 40ish for without any modifiers, not it's current number, that's at 15% crit damage). This happens on all weapons and not just vanilla; the second picture is a summon weapon (the sun spirit staff from calamity with only 10% extra crit damage on modifiers). I have both calamity death mode enabled and fargo's masochist's mod enabled as well, if that could be causing known (or unknown) issues.

![20180407155734_1](https://user-images.githubusercontent.com/38163806/38460348-8e55dc84-3a7d-11e8-9144-45bec203c6dd.jpg)

![20180407121510_1](https://user-images.githubusercontent.com/38163806/38460354-ba9445ce-3a7d-11e8-844b-e5debef36b29.jpg)

Modlist (in case any incompatibilities are known)
```
EvenMoreModifiers V0.0.10.1
Veinminer v1.3.0.4
AlchemistNPC v6.9.1
CalamityMod v1.3.1.1
Fargo's Mutant Mod (summons and souls) v0.16.2
Recipe Browser v0.6.1.3
Boss Checklist v0.1.5.3
Hero's Mod v0.2.0.2
Infinity - endless items v18.0
Thorium V1.4.3.8
Item Stats+ v1.3.2
Reduced Grinding v4.23
MoreAccessories+ v2.1
Yet another BHB v1.2.1
imksushi's v4.3.1
Magic Storage v0.4.3.1
```

i also have pictures of the gear i am using in the first picture as well as the accessory giving crit damage if you need those as well

**Comment by Jofairden** [comment]
Can you show the tooltips of those items? Thanks

**Comment by Bladewhisker** [comment]
i included ammo as well in case that was affecting anything, it's from infinity mod if that helps
![20180407155617_1](https://user-images.githubusercontent.com/38163806/38460400-a4f44092-3a7e-11e8-91b3-9bc2a9516ee5.jpg)
![20180407155619_1](https://user-images.githubusercontent.com/38163806/38460401-a9985c1e-3a7e-11e8-87e9-90093b764766.jpg)
![20180407155625_1](https://user-images.githubusercontent.com/38163806/38460402-ae97f9b8-3a7e-11e8-81dc-e1b6049286f6.jpg)

**Comment by Bladewhisker** [comment]
update: went through and tested without any other mods to rule out incompatibilities, still happens

(without any mods at all)
![20180407163407_1](https://user-images.githubusercontent.com/38163806/38460599-a90a49de-3a82-11e8-8429-478571ff8af5.jpg)

(this one was without infinity in case that was causing it, hence the hero's mod arrow at the bottom)
![20180407163719_1](https://user-images.githubusercontent.com/38163806/38460597-a5e05334-3a82-11e8-8217-830e235034fd.jpg)

**Comment by Jofairden** [comment]
Yep, I found the issue. Thanks for reporting!
