### ISSUE TITLE
Actual MapleStory Cubes to re-roll modifiers / Seperate re-roll for mod's modifiers

### ISSUE THREAD

**Issue by Jobinx** [Jofairden/EvenMoreModifiers#14]
I like the convenience of re-rolling the modifiers using Goblin Tinkerer.

But since this mod is inspired from MapleStory's cubing system, maybe you could add actual Cubes and have a window pop up similar to Maple. 
![images](https://user-images.githubusercontent.com/37463136/39090564-70f2262a-459f-11e8-94fc-251e9d4f58b4.jpg)
Maybe the Goblin Tinkerer could sell them. You could also craft them. And the more late-game you get, the better Cubes you can buy/craft (Epic, Unique, and Legendary rarities with better cubes).

But I have a feeling this would be difficult, and would take a long time to perfect. It's just an idea.

My second recommendation would be to add another slot for the Tinkerer to re-roll ONLY the mod's modifiers (doesn't re-roll Vanilla modifier).

![bonus reforge](https://user-images.githubusercontent.com/37463136/39090629-a17ce4e0-45a1-11e8-9351-872071c2faa1.png)

**Comment by Jofairden** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/Jofairden/EvenMoreModifiers/issues/11 (Modifiers roll on coins and vanity), https://github.com/Jofairden/EvenMoreModifiers/issues/7 (Modifiers are not rolled on generated content), https://github.com/Jofairden/EvenMoreModifiers/issues/9 (Items should be able to opt-out from rolling modifiers), and https://github.com/Jofairden/EvenMoreModifiers/issues/5 (Modifiers issues).

**Comment by Jofairden** [comment]
This is actually planned the way you describe it: almost a 1-to-1 copy of Maplestory's cubing with a Terraria flavour. I will need to figure out how they become accessible, but preferably from early on all the way to later on in the game. Obviously the stronger versions unlocking as players progress.

Adding a new tinkerer slot is virtually impossible, nor do I want to go that route: I want the tinkerer to remain what it is by default as much as possible. There will be a way to 'seal' modifiers on an item though, locking them in place even when using the tinkerer's service.

**Comment by Jofairden** [comment]
Hey, an update! A basic cube UI has been implemented already! More will come in the future. @Jobinx
