### ISSUE TITLE
% defense modifier giving infinite defense

### ISSUE THREAD

**Issue by Grravityy** [Jofairden/EvenMoreModifiers#16]
I got a "% defense" modifier on two pieces of equipment, it causes my defense to infinitely rise.

**Comment by Jofairden** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/Jofairden/EvenMoreModifiers/issues/5 (Modifiers issues), https://github.com/Jofairden/EvenMoreModifiers/issues/10 (Crit damage% modifier bugged? (applying too much bonus)), https://github.com/Jofairden/EvenMoreModifiers/issues/7 (Modifiers are not rolled on generated content), https://github.com/Jofairden/EvenMoreModifiers/issues/11 (Modifiers roll on coins and vanity), and https://github.com/Jofairden/EvenMoreModifiers/issues/9 (Items should be able to opt-out from rolling modifiers).

**Comment by Grravityy** [comment]
I found it only applied to an item in the extra accessory slot made by cheat sheet.

**Comment by Jofairden** [comment]
Thanks, that is helpful information.

**Comment by Grravityy** [comment]
Update, when multiple accessories have this enhancement, each enhancement seems to affect each other enhancement. I have pieces with 4%, 7%, , 7%, , 4%, 4%, 3%, , 4% for a total of 33% over 6 items. My base defense is 85, but my effective defense is 704 with the defense % enhancements. This is an 828% increase.

**Comment by Jofairden** [comment]
Well, can you please update the mod?
