### ISSUE TITLE
+X% crit multiplier gives crazy amounts of damage with crits

### ISSUE THREAD

**Issue by Gotoro** [Jofairden/EvenMoreModifiers#17]
I got Ninja Shirt from Slime Expert Bag which said "+8% crit multiplier". 
While my weapon is dealing 30 damage and ~60 with crits, when I put on this shirt I was getting ~50k damage with crits.
I tested it with Eye of Cthulhu, to see if it was a visual bug or not--
and no, it was a legit ~50k dmg dealt.
Though, re-logging in world fixed it and I couldn't recreate it, no matter what I tried.

I'm playing with other mods aswell, so it could be an issue.
I'm using v0.1.0.9 of the mod(I believe it's latest)
TModLoader - v.0.10.1.4

**Comment by Jofairden** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/Jofairden/EvenMoreModifiers/issues/10 (Crit damage% modifier bugged? (applying too much bonus)), and https://github.com/Jofairden/EvenMoreModifiers/issues/16 (% defense modifier giving infinite defense).

**Comment by Jofairden** [comment]
it's a bug with another mod. disable other mods 1 by 1 and find the culprit. because I tested crit multi and without other mods it works perfectly.
