### ISSUE TITLE
Light Giving Modifier Bug

### ISSUE THREAD

**Issue by macroboy** [Jofairden/EvenMoreModifiers#18]
Whenever you equip an accessory that gives a light boost, it lights up the whole screen, or just doesnt give any bonus at all unless you have two light giving acc. equiped which causes the problem
I have yet to determine if another mod is causing the issue, and will update the  thread if i find a fix.

**Comment by Jofairden** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/Jofairden/EvenMoreModifiers/issues/5 (Modifiers issues), https://github.com/Jofairden/EvenMoreModifiers/issues/10 (Crit damage% modifier bugged? (applying too much bonus)), https://github.com/Jofairden/EvenMoreModifiers/issues/16 (% defense modifier giving infinite defense), https://github.com/Jofairden/EvenMoreModifiers/issues/7 (Modifiers are not rolled on generated content), and https://github.com/Jofairden/EvenMoreModifiers/issues/11 (Modifiers roll on coins and vanity).

**Comment by macroboy** [comment]
I also have the crit. chance bug but not the vanity item/coin modifier bug, but the issue i have only applies to the light bonus. All other modifiers have no issues and work fine.

**Comment by Jofairden** [comment]
Which version are you on? It should be fixed..
