### ISSUE TITLE
Luck can cause insane magnitude rolls [needs investigating]

### ISSUE THREAD

**Issue by Spikestriker303** [Jofairden/EvenMoreModifiers#20]
Currently there is an issue, that is seemingly caused by the luck modifier, that causes you to roll insanely high numbers for modifiers. These include examples such as 1683% dodge chance or +972% max health and even if the modifiers are removed from any given item, or another is spawned in, the modifier number rolls stay high until both the item with luck is removed and the game is reset. This can cause a large downward spiral rather quickly because once one item has even a little luck it increases modifier number slightly, meaning if you get higher luck on something else you can use it for even larger numbers. Oh and as a side note, if you hold the cubes in your mouse while you reforge modifiers they don't get removed and can thus be used indefinitely.

**Comment by Jofairden** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/Jofairden/EvenMoreModifiers/issues/5 (Modifiers issues), https://github.com/Jofairden/EvenMoreModifiers/issues/18 (Light Giving Modifier Bug), https://github.com/Jofairden/EvenMoreModifiers/issues/9 (Implement a modifier rolling rules system), https://github.com/Jofairden/EvenMoreModifiers/issues/11 (Modifiers roll on coins and vanity), and https://github.com/Jofairden/EvenMoreModifiers/issues/16 (% defense modifier giving infinite defense).

**Comment by Jofairden** [comment]
Hey, thanks for the report. The issue is known to me, however I don't yet know what causes it. Can you share you entire modlist?

For the second issue, I'll make a second thread for that.

**Comment by Spikestriker303** [comment]
I have quite a large number of mods in my current pack but I was able to reproduce this particular bug with only this mod enabled using the black cube and any accessory. Using the aforementioned cube bug to use the black cube until the accessory received luck. At which point I put the luck accessory in an accessory slot and repeated with a separate accessory, so as to obtain a higher luck value such as +38 luck, and once that accessory was also equipped modifier numbers start to rise exponentially the more you forge any item at all that is able to have one. This could not only be due to the amount of luck on an item but the black cube's inherent 25% chance for a better modifier.

**Comment by Jofairden** [comment]
Nah, there's definitely something broken here. The black cube being able to roll 25% stronger inherently only means that the maximum magnitudes go up by 25%. I'll have to look into this

**Comment by Jofairden** [comment]
The weird thing is, I cannot seem to trigger this bug. I currently have over 60 luck and I'm rolling fairly normal ranges.

**Comment by Spikestriker303** [comment]
ok, i am currently turning all my mods on one by one because after restarting i couldn't produce the bug with just this mod on so i must have managed to not turn one of the mods off last time

**Comment by Spikestriker303** [comment]
I can seemingly only get it to work on my original character and not my test character so it could have something to do with either progression or quite possibly how many accessories i have for some reason since i'm using functional vanity accessories. though that should mean it would trip off just the same on my test character but it is something to consider at least

**Comment by Spikestriker303** [comment]
upon further examination it is indeed how the luck stat works when put into a vanity slot when using functional vanity accessories

**Comment by Jofairden** [comment]
Thanks for the info. I managed to fix the problem. Next release everything should work fine.
