### ISSUE TITLE
Character Wipe/Crash

### ISSUE THREAD

**Issue by IsaiahJM97** [Jofairden/EvenMoreModifiers#22]
I should first off state I am friends with the guy who earlier reported the glitch in the mod about the high stat numbers with the luck stat while rolling new modifiers, it was something we were both experiencing and thank you for fixing it. I am now having a new issue though. 
I updated the mod and joined his world and we were playing and after a while, I got kicked and when I tried to load my character, I saw the thumbnail of my character and he has been wiped to default, with 100HP and 0MP. My time on the character still shows. I notice there is an error on this character now 
**(Log will be linked at the end)**
I did thankfully back up the mod and character prior to updating, so I was able to restore them both. I found that I restore them and reforged an item I thought might be the issue.
I had an item with +113% Ranged Crit Chance, +113% Ranged Damage, +113% Ranged Damage, +113 luck and that the one I reforged. I did not have any issues at all after that. I quit the game, updated and joined the server back and had no issues. 
While playing I had suffered from a lag spike and my game stopped working on my end and then I decided to relog into the server and when I went to select the character, I noticed once again I had the same error as earlier.
[Runtime Error.txt](https://github.com/Jofairden/EvenMoreModifiers/files/2403593/Runtime.Error.txt)

**Comment by Jofairden** [comment]
Update your mod, I fixed it
