### ISSUE TITLE
Recent Update Causing Issues

### ISSUE THREAD

**Issue by LeoVeracruse** [Jofairden/EvenMoreModifiers#23]
Since the most recent update of this Terraria mod on April 14,2018 I have had the problem of not a single modifier will got above 20. Weapons, Armor, and Accessories are all affected by this bug. I have tested this across maps and across characters with no change in effect.

**Comment by Jofairden** [comment]
It's not a bug, it's intended. Please read the changelogs: https://headwayapp.co/even-more-modifiers-changelog/v0-1-2-0-73243
