### ISSUE TITLE
Dealing Tons of Damage

### ISSUE THREAD

**Issue by Smaxtr** [Jofairden/EvenMoreModifiers#26]
It has to to do with the "Deal ?% Danke vs. max Health Enimies"
Cause when I hit a max health Enemy they instantly die no matter what (Except Dungeon Guardian)
But when they lose health from Thorns or Inferno Potion and then I hit them, they won't die instantly.
It is really big and game changing since you can easily rush through all boses with no effort.

**Comment by Jofairden** [comment]
Update this mod and wing slot and anti social if you have them

**Comment by pPkMnh4to8994h** [comment]
Same. Weapons deals a LOT of damage, although this occurs randomly, i'm not even sure what causing it, but since this mod messes with damage multipliers like no one does, i think cause of this is somewhere here.
https://imgur.com/a/tlQQkav

**Comment by Jofairden** [comment]
Well, I need more information. Are you using wing slot and/or anti social? And what are the mod versions? I need a mod list with versions.

**Comment by pPkMnh4to8994h** [comment]
Here you go:
Reduced Grinding v4.32
DNI Equipment Upgrade v1.3.2
Shader Library v2.0.2
Item Customizer v2.0
Health And Mana From Bosses v1.1.2.1
Mod of Redemption v0.6.0.1
Boss Checklist v0.1.6.1
Wing Slot v1.6.2
EvenMoreModifiers v0.1.2.3
MagicStorage v0.4.3.3
Piercing Projectile Fix v1.3
OmniSwing v2.1
Fishing 2.0 v1.4.5
Calamity Mod v.1.3.4.1
Cheat Sheet v0.4.3.1
Buffed damage over time Debuffs v0.3.0.2
ReforgeArmor v1.0

**Comment by Jofairden** [comment]
Thx, can you confirm that this also happens with just this mod enabled? Most people seem to not be able to, so I'm still unsure what causes it (no longer have this buff)
Make sure to unequip your wing in wing slot mod too, because it was buggy in past releases. If both mods are updated it should work though.
