### ISSUE TITLE
Can't reforge Armor

### ISSUE THREAD

**Issue by Chiyah** [Jofairden/EvenMoreModifiers#34]
I can't even place the Armor on the reforge box on the tinkerer. Tried if it was a mod conflict Created a new character, new world and only enabled CheatSheet and this Mod so that I can spawn the tinkerer in, and I still can't place the armor in the reforge box.

I don't want to use cubes as they do not reroll the initial prefix on an item. I've no idea what to do now?

**Comment by Jofairden** [comment]
This sounds very odd. So what is your total mod list? Only EMM and Cheat Sheet? I will definitely have to look into it then. Can you try a full restart with only those 2 mods enabled, or potentially only EMM enabled? I'm fairly sure it _should_ work with just EMM, other mods may cause conflict.

**Comment by Jofairden** [comment]
Ok, the issue is found. Try setting UI zoom to default 100%, and regular resolution. I'll make sure it's fixed in v1.0. You can track #41 for progress.
