### ISSUE TITLE
Item getting deleted when exiting game with item in cube interface

### ISSUE THREAD

**Issue by Steve4448** [Jofairden/EvenMoreModifiers#46]
I was using the Black Cube to get better modifiers and before taking the item out of the interface I exited the game (via Save & Exit). Upon coming back to the game my item was gone. Just to make sure, I was able to reproduce the issue by trying another item and it too got deleted.

Also thanks for a great mod!

**Comment by Jofairden** [comment]
Hmm that is odd. I know for sure at least on Github there's code that will give you back the item before you exit. It's right here:  https://github.com/Jofairden/EvenMoreModifiers/blob/rework/Loot.cs#L57 & https://github.com/Jofairden/EvenMoreModifiers/blob/235890f15c1ce4382ae60146166a11b778520c2e/UI/Tabs/Cubing/GuiCubingTab.cs#L275-L284 I guess this code is not yet part of the old releasea 😅 (currently on the browser)

**Comment by Steve4448** [comment]
Ah okay, I'll close this issue then. :smile:
